apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: ping-demo
  name: ping-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: ping-demo
  template:
    metadata:
      labels:
        k8s-app: ping-demo
    spec:
      containers:
        - image: harbor.k8s.gome.inc/demo/ping:v1
          imagePullPolicy: IfNotPresent
          name: ping
          ports:
            - containerPort: 9080

---

apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: ping-demo
  name: ping-demo
  namespace: default
spec:
  selector:
    k8s-app: ping-demo
  ports:
    - port: 9080
      targetPort: 9080

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ping-demo
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: ping-demo
              servicePort: 9080
      host: demo.k8s.gome.inc
